#!/bin/bash

# DiPoHLo - Distribuição Portável do HotLogo
#
# Build Script
#
# Arkanon <arkanon@lsd.org.br>
# 2015/07/02 (Qui) 00:12:35 BRS
# 2015/07/01 (Qua) 00:53:04 BRT

    NAME="Portable HotLogo Distribution - PHoLD"
     MAJ="0.11.0"
     BLD=$(($(tail -n1 build-history 2> /dev/null | cut -f1)+1)) # update build number
     VER="$MAJ-$BLD"

     rpm="ftp://rpmfind.net/linux/fedora/linux/development/rawhide"
      sf="http://downloads.sourceforge.net/openmsx"
    pref="openmsx-$MAJ"

  # emulador
  arch[0]="4.fc23.i686"   ; pkg[0]="$rpm/i386/os/Packages/o/$pref-4.fc23.i686.rpm"
  arch[1]="4.fc23.x86_64" ; pkg[1]="$rpm/x86_64/os/Packages/o/$pref-4.fc23.x86_64.rpm"
  arch[2]="win.x86"       ; pkg[2]="$sf/$pref-windows-vc-x86-bin.zip"
  arch[3]="win.x64"       ; pkg[3]="$sf/$pref-windows-vc-x64-bin.zip"
  arch[4]="mac.x86_64"    ; pkg[4]="$sf/$pref-mac-x86_64-bin.dmg"

  # dependencias
  dep[0]="$rpm/i386/os/Packages/l/libao-1.2.0-5.fc23.i686.rpm"
  dep[1]="$rpm/x86_64/os/Packages/l/libao-1.2.0-5.fc23.i686.rpm"

  export TIMEFORMAT='  ELAPSED TIME: %lR'

  echo -e "$BLD\t$(LC_TIME=C date +'%Y/%m/%d (%a) %H:%M:%S %Z')" >> build-history

  mkdir -p $MAJ
  (
    cd $MAJ

    mkdir -p bin
    mkdir -p share

    mkdir -p pkg
    (
      cd pkg

      for i in $(seq ${#pkg[*]})
      do

          n=$((i-1))
        url=${pkg[$n]}

        echo ${url##*/}

        time wget -qc $url

        mkdir tmp
        (
          cd tmp

          case ${arch[$n]} in

            *fc*)
                  7z e -so ../${url##*/} 2> /dev/null | cpio -idm --quiet
                  rm                          usr/share/openmsx/settings.xml
                  mv etc/openmsx/settings.xml usr/share/openmsx
                  mv usr/bin/openmsx          ../../bin/$pref-${arch[$n]}
                  mv usr/share/openmsx/       ../../share/${arch[$n]}/
                  ;;

            win*)
                  7z x ../${url##*/} &> /dev/null
                  mv codec/      share/
                  mv openmsx.exe ../../bin/$pref-${arch[$n]}.exe
                  mv share/      ../../share/${arch[$n]}/
                  ;;

            mac*)
                  7z x ../${url##*/} &> /dev/null
                  7z x 4.hfs         &> /dev/null
                  mv openMSX/openMSX.app/ ../../bin/$pref-${arch[$n]}.app
                  ;;

          esac

        )
        rm -r tmp

      done

    )

  # # ldd usr/bin/openmsx | grep 'not found'
  # # usr/bin/openmsx: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by usr/bin/openmsx)
  # #   libSDL_ttf-2.0.so.0 => not found
  # #   libpng16.so.16 => not found

  # mkdir -p dep
  # (
  #   cd dep

  #   for i in $(seq ${#dep[*]})
  #   do
  #     time wget -c ${dep[$((i-1))]}
  #   done

  # )

  )

# EOF
