#!/bin/bash

# Arkanon <arkanon@lsd.org.br>
# 2014/03/07 (Fri) 00:52:56 (BRS)
# 2014/03/05 (Wed) 22:21:10 (BRS)
# 2013/04/15 (Seg) 05:49:49 (BRS)

version=0.6.0

mkdir -p pkg

mkdir -p $version
cd       $version

   touch v$version

   omsx=0.10.0
   (cd ../pkg && curl -sOC- http://aarnet.dl.sourceforge.net/project/openmsx/openmsx/${omsx}/openmsx-${omsx}-windows-vc-x86-bin.zip)
   unzip -qq ../pkg/openmsx-${omsx}-windows-vc-x86-bin.zip
   mv openmsx.exe openmsx-bin.exe

   (cd ../pkg && curl -sOC- http://ftp.us.debian.org/debian/pool/main/o/openmsx/openmsx_${omsx}-1_i386.deb)
   alien -tc ../pkg/openmsx_${omsx}-1_i386.deb
   tar   zxf        openmsx-${omsx}.tgz
   mv usr/bin/openmsx openmsx-bin

   glew=1.10
   (cd ../pkg && curl -sOC- http://ftp.us.debian.org/debian/pool/main/g/glew/libglew${glew}_${glew}.0-3_i386.deb)
   alien -tc ../pkg/libglew${glew}_${glew}.0-3_i386.deb
   tar   zxf        libglew${glew}-${glew}.0.tgz
   mkdir -p lib
   mv usr/lib/i386-linux-gnu/libGLEW.so.1.10.0 lib/libGLEW.so.1.10

   rm *.tgz

#  cp -a share .share

   rm -r Catapult doc install usr

   (
     cd ../pkg
     prefix=http://www.msxarchive.nl/pub/msx/emulator/openMSX/System%20Roms/Gradiente
     curl -sOC- $prefix/expert_ddplus_basic-bios1.rom
     curl -sOC- $prefix/expert_ddplus_disk.rom
     sha1sum *.rom
     # d6720845928ee848cfa88a86accb067397685f02  expert_ddplus_basic-bios1.rom
     # f1525de4e0b60a6687156c2a96f8a8b2044b6c56  expert_ddplus_disk.rom
   )

   (

      cd share

      rm -r icons nettou_yakyuu playball extensions
      rm -r unicodemaps/unicodemap.{??,j*,br_hotbit*,proto_fr}
      rm -r skins/handheld
      rm -r skins/none
      rm -r skins/set?
      rm -r skins/*.png

      # scripts/ - carga de skin e do console
      # Vera     - teclado virtual
      # VeraMono - console

      mv machines/{README,Gradiente_Expert_DDPlus.xml} .
      rm -r machines/*
      mv README Gradiente_Expert_DDPlus.xml machines

      cp -a ../../pkg/*.rom systemroms

   )

   mv    share/skins/fancy  share/skins/set1
   cp -a ../data/*.xml      share
   cp -a ../data/software/* share/software
   cp -a ../data/frame.png  share/skins/set1
   cp -a ../data/pixel.png  share/skins
   cp -a ../data/disk       .
   cp -a ../data/misc       .
   cp -a ../data/openmsx*   .

   mod=../data/cygwin
   ori=/export/data/soft/cygwin/cygwin
   dst=/export/home/arkanon/public_html/svl.lsd.org.br/appsweb/svl/.h/msx/emu/distro/$version/cygwin
   mkdir -p $dst
   (
     cd $mod
     find . -type f | while read f
     do
       ( cd $ori ; cp -a --parents $f $dst 2> /dev/null ) || ( cd $ori/fs ; cp -a --parents $f $dst )
     # ( cd $ori ; grep -aq '^!<symlink>' $ori/$f && cp -a $(grep -aEo '[^/].*$' $ori/$f) $dst/$(echo $f | cut -d/ -f2-) )
     done
   )
   cp -a ../data/profile cygwin/etc

   # diff -u ../../.share/scripts/load_icons.tcl load_icons.tcl >| ../../../data/load_icons.tcl.patch
   patch -p1 share/scripts/load_icons.tcl < ../data/load_icons.tcl.patch

#  PARAMETROS="-script openmsx.tcl -machine Gradiente_Expert_DDPlus -cart share/software/hotlogo.rom -diska disk"
#
## OPENMSX_SYSTEM_DATA=share
#  LD_LIBRARY_PATH=lib OPENMSX_USER_DATA=share ./openmsx-bin $PARAMETROS
#
#  wine openmsx-bin.exe $PARAMETROS

# EOF
