#!/bin/bash

# SFX Package Maker
#
#   Arkanon <arkanon@lsd.org.br>
#   Piter Punk <piterpk@terra.com.br> (original idea)
#
#   v0.3  2011/07/29 (Sex) 20:53:11 (BRS)
#   v0.2  2011/07/17 (Dom) 09:29:56 (BRS)
#   v0.1  2003/02/11 (Ter) 11:10:33 (EDT)

#     pkgfile := sfxfile.tar.<gz|bz2|xz>
#     tar <z|j|J>c[v]f pkgfile <dirname|filesnames>
#     cat $(which ${BASH_SOURCE[0]}) pkgfile >| sfxfile
#     chmod +x sfxfile

# Depends on:
#
#   basename
#   bash
#   bzip2
#   cat
#   chmod
#   cut
#   dirname
#   echo
#   file
#   gzip
#   ls
#   mkdir
#   mv
#   readlink
#   rm
#   sed
#   tail
#   tar
#   wc
#   which

  this=$( [ "$FUNCNAME" ] && echo $FUNCNAME || basename ${BASH_SOURCE[0]} )

  dest=${temp:=/tmp}/openmsx-dist.$$
 udest="$this-content"
  skip=$[$(sed '/^#EOS#$/,$d' $0 | wc -l)+2]



if [ $(cat $0 | wc -l) -lt $skip ]
then

  if [ $# = 0 -o "$*" = "-h" ]
  then
    echo "Uso: $this  source_dir_name  dest_sfx_file"
    exit
  fi

  dirname=$1
  sfxpref=$2
  pkgpref=$(readlink -m $sfxpref)
  pkg_dir=$(dirname     $pkgpref)
  pkgpref=$(basename    $pkgpref)
  tmpfile="/tmp/$pkgpref-dist.$$"

   follow="-l"
    level="-mx=9"
   method="-m0=lzma"
     dict="-md=64m"
     word="-mfb=273"
    solid="-ms=on"

  echo -n "Creating Linux SFX..."
  sfxfile="$sfxpref.bin"
  pkgfile="$pkgpref.tar.bz2"
  ( cd $dirname && tar jcf $tmpfile . && mv $tmpfile $pkg_dir/$pkgfile )
  cat $(which ${BASH_SOURCE[0]}) $pkg_dir/$pkgfile >| $sfxfile
  chmod +x $sfxfile
  echo " done"

  echo -n "Creating Windows SFX..."
  sfxfile="$sfxpref.exe"
  pkgfile="$pkgpref.7z"
  ( cd $dirname && 7z a $follow $level $method $dict $word $solid $tmpfile . > /dev/null && mv $tmpfile $pkg_dir/$pkgfile )
  cat $dirname/misc/7z_sfx/{7zsd_lzma2-1.5b.sfx,cfg.txt} $pkg_dir/$pkgfile >| $sfxfile
  echo " done"

  exit

fi



[ "$*" = "-u" ] && dest=$udest

mkdir -p $dest

if [ $? = 0 ]
then

  type=$(tail -n +$skip $0 | file -b - | cut -d\  -f1)
  tail -n +$skip $0 | $type -d | tar -xf - -C $dest 2> /dev/null

  [ "$*" = "-u" ] && exit

# [ $(ls -1 $dest | wc -l) = 1 ] && cd *
  run=$dest/${run:=openmsx}

  if [ -e $run ]
  then
    export  EXTRA_OPT="u"
    export EXTRA_HELP="\n\n   -u descompacta o conteudo do executavel para '$udest'\n        (deve ser o unico parametro, se for usado)"
    . $run $*
    rm -r $dest
  else
    echo "'run' script not found."
    echo "Set an apropriable 'run' variable."
  fi

else
  echo "Permission denied to create $dest"
  echo "Set an apropriable 'temp' variable."
fi

rm -rf $dest

exit



#EOS#
